// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk6ikvVM0S5-hGHeYz0jqq0FfURDfAppc',
    appId: '1:1005874615921:android:a29d18877fcce86076edd0',
    messagingSenderId: '1005874615921',
    projectId: 'marketplace-5cc2f',
    storageBucket: 'marketplace-5cc2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSzUGI6dodMCcG1zKdJF_ilHyZ3XBFQpo',
    appId: '1:1005874615921:ios:9b3fa346afbfc35376edd0',
    messagingSenderId: '1005874615921',
    projectId: 'marketplace-5cc2f',
    storageBucket: 'marketplace-5cc2f.appspot.com',
    androidClientId: '1005874615921-j4opadpp1fne6f6jvkcqg308k4sq9hsn.apps.googleusercontent.com',
    iosClientId: '1005874615921-54qhmekns7cm08a9k1s5gdhe87kb55ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopdroid',
  );
}
